language: c

compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  - sudo pip install -U cpp-coveralls

script: make && make lib && python setup.py build && cd test && make test && python python_lib_test.py

after_success:
  - gcov --version; coveralls --verbose --gcov-options '\-lp' -r .. -E '.*testset' -E '.*faultymalloc'
