language: c

compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  - sudo pip install cpp-coveralls

script: make && cd test && make test

after_success:
  - coveralls -e faultymalloc.gcno -e testset.gcno --gcov-options '\-lp'
