language: c

compiler:
  - clang
  - gcc

branches:
  only:
    - master

before_install:
  - sudo pip install cpp-coveralls

script: make && cd test && make test

after_success:
  - coveralls --verbose --gcov-options '\-lp' -r .. -E '.*testset' -E '.*faultymalloc'
